backend:
  name: github
  repo: Benaiah/netlify-cms-test-Repo
  branch: master

media_folder: "media"
public_folder: "content"

extend_config_with: "config-extension.yml"

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    files:
      - name: "config-extension"
        label: "Site Settings"
        file: "config-extension.yml"
        description: "CMS Config"
        fields:
          - {label: "Publish Mode", name: "publish_mode", widget: "select", options: ["editorial_workflow", "simple"]}
          - {label: "Media Folder", name: "media_folder", widget: "string"}
          - {label: "Public Folder", name: "public_folder", widget: "string"}
          - label: "Test Things"
            name: "test_things"
            widget: "object"
            collapse:
              startCollapsed: true
              summary: "Collapsed!"
            fields:
              - label: "Change Me"
                name: "change_me"
                widget: "boolean"
              - label: "Inner test thing"
                name: "inner_test_thing"
                widget: "object"
                collapse:
                  startCollapsed: true
                  summary: "Collapsed"
                fields:
                  - label: "Change Me"
                    name: "change_me"
                    widget: "boolean"

          - label: "Collections"
            name: "collections"
            widget: "object"
            repeat:
              idField: "name"
              singularLabel: "Collection"
            collapse:
              startCollapsed: true
              summary:
                fields: ["label"]
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - label: "Can create new entries"
                name: "create"
                widget: "boolean"
              - label: "Editor Settings"
                name: "editor"
                widget: "object"
                collapse:
                  startCollapsed: true
                  summary: "Settings for the entry editor page."
                fields:
                  - {label: "Preview", name: "preview", widget: "boolean", defaultValue: true}
              - label: "Fields"
                name: "fields"
                widget: "object"
                repeat:
                  idField: "name"
                  singularLabel: "Field"
                collapse:
                  startCollapsed: true
                  summary:
                    fields: ["label"]
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "Name", name: "name", widget: "string"}
                  - label: "Widget"
                    name: "widget"
                    widget: "select"
                    options:
                      - { label: "Boolean", value: "boolean" }
                      - { label: "String", value: "string" }
                      - { label: "Object", value: "object" }
                      - { label: "List", value: "list" }
                      - { label: "Markdown", value: "markdown" }
